### ISSUE TITLE
SPI question

### ISSUE THREAD

**Issue by MarcFinns** [Bodmer/TFT_ILI9341_ESP#2]
Hi Bodmer, I was looking for a fast ILI9341 lib for ESP8266 and i found yours.
A couple of questions, before I dig into it...
1) Is it using hardware SPI?
2) can I use GPIO16 as SS/CS? (it is the only one i have available in my project)
thanks for now!

**Comment by Bodmer** [comment]
Hi, To answer your questions:

1. Yes
2. Yes GPIO16 is called D0 in the Arduino environment

**Comment by MarcFinns** [comment]
Thanks.
Last one: I read in many places that this display can work with 4 wires but i count 5 instead (miso mosi sck cs dn)
Where is the mistake...? Thanks again!

**Comment by Bodmer** [comment]
The display can work in two interface modes that are quoted as 4 wire, these are described in the data sheet at Interface I and Interface II.

- Interface I uses a single bidirectional SDA line for input and output data (SDA, SCK, CS, DC)
- Interface II uses separate data wire for input and output data (MISO, MOSI, SCK, CD, DC) which is actually 5 wires!

There is also a 3 wire mode where the DC bit is part of the serial stream.

Most Arduino targeted displays are configured as 4 wire Interface I or Interface II by hidden links.

If you use a Interface I then MISO can be wired but is not used, in this case the SPI cannot read data on the MOSI line but it can send it to the display normally.  To receive data on the MOSI line you would need to disable the SPI and bitbash the read commands, turning the SDA (i.e MOSI) line to input at the correct time to clock in bits.

If you use and Interface II display and do not read data from the display then the MISO line does not need to be connected, however the MISO line cannot also be used for another function.

**Comment by MarcFinns** [comment]
Thanks for your time Bodmer, appreciated!
The only missing bits of info is whether there is a driver that supports 4 wire in either modes / why i cant use MISO line for something else in mode II... and thanks again!

**Comment by Bodmer** [comment]
In tests I have found that the hardware MISO cannot be used for any other function when the SPI mode is active, I did not investigate whether this limitation is intrinsic in the design of the ESP8266 chip or is due to the way the ESP8266 is configured and used by the Arduino SPI library. If you could find the answer to this question and manage to find a solution then do let me know as this would be useful.

**Comment by MarcFinns** [comment]
Ok, I will give it a try and let you know.
I also see that in a project of yours you play with hardware scrolling. Is it implemented in this library?

**Comment by MarcFinns** [comment]
UPDATE: I managed to make the display work with a record low number of pins...
CS always selected; MOSI and CLK standard; Reset connected to the ESP reset; D/N GPIO16.
I can actually use the hardware MISO, for example i use it (with a transistor) to control the display LED backlight. All I had to do is to set the pinMode after the tft.init(0 call.
What I could not manage however is to use it to drive D/C.
Comments / suggestions?

**Comment by Bodmer** [comment]
The hardware scrolling is not in the library, the required functions are in the sketch and they should be portable to use in a sketch with the ESP8266.

My findings were that the pin function can be changed after init() but as soon as an SPI transaction occurs the pin reverts to being MISO during the transaction. Are your findings different?

**Comment by MarcFinns** [comment]
I find your described behaviour very logical. Transactions require bidirectional communication hence MISO. The receiving logic in the driver is probably reconfiguring the Miso as input. 
However, if you don't use transactions, that logic is never invoked. This is in fact what I am doing. 
On the other subject, why not integrating the hardware scrolling in the lib? Let me know if interested in doing it / if you have a starting point if you are not thinking of doing it. And thanks again.

**Comment by Bodmer** [comment]
There is a [hardware scrolling sketch here](http://www.instructables.com/id/Arduino-serial-UART-scrolling-display-terminal-usi/).

I have considered adding it to the library and it is on my To Do list.

**Comment by MarcFinns** [comment]
There is a [LIBRARY](https://github.com/prenticedavid/MCUFRIEND_kbv) that extended the GFX API to add also hardware scrolling but it is for parallel displays. Could it be a starting point?

**Comment by Bodmer** [comment]
Yes, you could use the same "glue" method of extending the TFT_ILI9341_ESP library.

**Comment by MarcFinns** [comment]
...are you ever going to do it..?

**Comment by Bodmer** [comment]
Yes, it is on the "To Do" list but I am working on another 2 projects at the moment with the JPEGDecoder library so it will be a few weeks before it is done, tested and uploaded.

There will be two new functions setupScrollArea() and scrollAddress().  These are quite small functions and are included in the attached two sketches which will show you how it works.  I recommend reading the ILI9341 datasheet as scrolling is one of the more esoteric functions and if you want to plot in the scrolled area you need to realize that the coordinates also scroll!  This is handled in the attached sketches.

As the required functions are so small it should not be a problem including them in your sketches until I get around to adding them.

Have fun.

[Scrolling sketches.zip](https://github.com/Bodmer/TFT_ILI9341_ESP/files/767870/Scrolling.sketches.zip)

**Comment by MarcFinns** [comment]
Ok, will look into it. Thanks. I do understand that coordinates also move and in fact that's why I was suggesting to handle it in the library to make it user transparent. Ideally from the caller point of view they should remain fixed. Thanks again and enjoy your new projects!

**Comment by Bodmer** [comment]
Let me know what scrolling features you might like to see in the library. Not many people seem to want the facility so it has not been a priority to add it. The Serial Terminal sketch does make good use of it. It is a pity that scrolling is only in one plane, mostly I use the displays in landscape mode, though the horizontal viewing angle range is not so good in that orientation. I suspect the reason is that the displays were designed for phone use.

Transparent handling of the coordinates is tricky and will slow graphics operations down significantly because the display can be divided in to 4 zones that have coordinate discontinuities between them and so the graphics window addressing would need to take this into account plus the defined rotation.

Some simple scrolling functions are possible though, as demonstrated in the example sketches.

**Comment by MarcFinns** [comment]
Hi Bodmer, thanks for replying.
Let me structure my reply in 3 points:
1)	SCROLLING: I am building a cool device that pushes the ESP to the limit… it measures from a lot of sensors and logs to MQTT + displays on LCD, handling several pages that can be swiped through via a gesture sensor. One of the features is to plot the history of the measurements, hence I would need a chart that scrolls to the left as new samples become available. As the vertical axis on the left shall stay in place as well as the top bar that displays time and wifi status, the possibility of scrolling a window only is enticing. I guess I could just redraw it but the thing needs to be responsive and the HW scrolling is appealing… 
In this scenario the ideal option would be if the API would provide the option to still reason in terms of absolute / physical LCD coordinates. The HW scroll would just shift the window to the left (erasing the outgoing portion) and I would continue plotting on the right end side. 
Now, I imagine that the ILI9341 does not really move data in the framebuffer but adjust a pointer… hence the coordinates calculation becomes messy.
Not sure if this is what you had in mind / what your sketch is doing, I did not have time yet 
to open it. I have seen 

2)	HARDWARE SUPPORT: I see that to boost speed your lib is accessing ESP8266 registers directly. This however fails when using GPIO16/D0. I solved the problem by modifying the lib and reverting to digitalWrite. This is FYI. While it would be nice not to have a custom lib, I can live with it

3)	BUG?: I believe i found a bug in the library. It appears it does not honor the background colour setting when using TL_DATUM. Basically, re-writing in the same location becomes a mess after a while as the background color is not applied. I can send you the test code or a picture but I guess it is clear. It is also a minor one as I can use other datum settings.

4)	By the way, do you know of any good looking charting library or do I need to write it myself?

Thanks for your time an happy hacking.

**Comment by Bodmer** [comment]
To answer your points:
1. You may find the hardware scrolling is too restrictive as the scrolled area must be the full width of the display in portrait orientation (but only scrolls up/down) and full height in landscape orientation (but only scrolls left/right). If that is OK then it is an option. I have coded scrolling graphs for an oscilloscope project and used an array as a circular buffer and re-plotted the trace for each scroll increment by erasing each trace pixel and plotting in new position while moving the pointer on x axis, this is a flicker free method and keeps the SPI traffic down so works fast even on an AVR processor.
2. Yes, I just tried using D0 and it must be handled differently, I will investigate. digitalWrite used to be quite slow on AVR processors but maybe it is more efficiently coded on the ESP8266 and direct register writes do not speed things up much compared to the SPI traffic delays.
3. Ah! I thought I had fixed that but I see that was in another variant of the library. You can patch the code [as corrected here](https://github.com/Bodmer/TFT_ILI9341_ESP/blob/master/TFT_ILI9341_ESP.cpp#L2353) and remove the variable assignment later in the function.
4. [This sketch is for a different display](https://github.com/Bodmer/TFT_HX8357/tree/master/examples/Graph_2) but perhaps is suitable and can be adapted.

TTFN

P.S I have just uploaded a new version of the library I have been working with, this included some more bug fixes and new (effectively duplicate) functions that do not need the font reference to be included (including the font to be used was a legacy feature before setTextFont() was added).

**Comment by MarcFinns** [comment]
thanks for now.
by the way the planespotter color is AMAZING

**Comment by Bodmer** [comment]
No quite as amazing but still fun is the squix weather station, [here is a tweaked version](https://github.com/Bodmer/esp8266-weather-station-color).

**Comment by MarcFinns** [comment]
Thanks!
What IDE do you use? I have reached the limit of the native Arduino i guess...

**Comment by Bodmer** [comment]
Arduino IDE 1.8.1 currently.
What limit have you reached?

**Comment by MarcFinns** [comment]
Too many files, really.
I'd love to split in libs and  edit them at the same time as the main project.
I know it is possible using visualStudio and the related plugin but I am on a mac. I tried eclipse but it forces to modify projects in a way that makes them not compatible with arduino anymore. The xcode plugin...i am allergic. I was wondering whether another IDE is available without going windoze

**Comment by Bodmer** [comment]
I do the same and use Notepad++ in Windows 7, it has all the C/C++syntax (plus lots of other language) colouring and handles multiple tabs. It allows windowing into different parts of the same file, files in separate windows and lots of other features for find/macros etc. Not sure if there is a Mac equivalent.

[PlatformIO](http://platformio.org/platformio-ide) may suit your needs for an integrated IDE and is worth a look.

**Comment by MarcFinns** [comment]
On the digitalWrite vs direct register access, I saw you changed it on CS but not on D/C.
I run some tests running UTFT_DEMO and comparing the run tie as displayed by the sketch:
  D/C on  D0 with digitalwrite = 1440
  D/C on  D3 with digitalwrite = 1240
  D/C on  D3 with register access = 1180
In my opinion the gain is not worth giving up the possibility to use D0...
my 2c

**Comment by Bodmer** [comment]
Using digitalWrite has different impacts depending on the graphics function called. The impact on dawPixel is more significant and this then impacts other functions that use it like drawing a circle outline. Block fill operations suffer less as there are fewer line toggles compared to the number of pixels transferred.  If D0 must be used then allocate CS to it as this toggles less fequently.

You suggestion to allow D0 to be used is good, so I have added the option to accomodate this in the User_Config.h file. See the latest version of the code. Users can then make a choice basrd on available pins and performance needs. Thanks again for your input.

**Comment by MarcFinns** [comment]
Thanks!
I am abusing the ESP (will share the project at some point) so I have no pins available anymore - hence the need to use D0. 
As I don't use MISO, I actually wanted to use D6 as D/C but it does not work. I use it for controlling the backlight instead. Also, I leave CS always active, as I have only one SPI device. 
Question: if not using MISO and CS, is it correct to set them to -1 in the config file? It works, but I wanted to be sure that it is also correct. Thanks again!

**Comment by Bodmer** [comment]
MISO is not configured by the library as it is assumed that the hardware SPI port is being used.

CS, good question, it depends on how the pin setting code in the underlying board package treats negative values. So I have not looked at that.  I think to be "safe" given this unknown I should add another option to the User_Setup file.

**Comment by MarcFinns** [comment]
It would be great if you added that flag... I hate having custom libraries!
Thanks.

**Comment by Bodmer** [comment]
Done!

**Comment by MarcFinns** [comment]
thanks!

**Comment by MarcFinns** [comment]
Hi Bodmer, I see that this lib is not being developed anymore. Therefore I would like to migrate my current project to the new one. Are these API-compatible? for example, would your porting of the planespotter work?
thanks!
